### ISSUE TITLE
php artisan migrate error

### ISSUE THREAD

**Issue by udemethegrtman** [Oviyum/laravel-otp#12]
λ php artisan migrate
Migrating: 2017_08_13_185658_create_otp_logs_table

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `one_time_password_logs` add constraint `one_time_password_logs_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)

  at C:\laragon\www\gazelle_web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint")
      C:\laragon\www\gazelle_web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

  2   PDOStatement::execute()
      C:\laragon\www\gazelle_web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:458

**Comment by codingquark** [comment]
@udemethegrtman thanks for reporting!

Have you investigated it more? The trace suggests it is not able to add the constraint, but does not speak of why. Perhaps the table does not exist, or the column names are different etc.

**Comment by udemethegrtman** [comment]
The table exits `user`, what column names are diffrent?

**Comment by codingquark** [comment]
I was speculating. Some more investigative data will help. I won't be able to help with what I have right now.

**Comment by codingquark** [comment]
Due to no reply for a week, closing it. Please reopen if there is something to be added.
