### ISSUE TITLE
I need document usage

### ISSUE THREAD

**Issue by louis-hoang21** [Oviyum/laravel-otp#13]
Now document is not clear how to use.
I can't call make otp, you only talk about the package provides with the following helpers but not clear
I need example this package
Can somebody help me?
Thank you.

**Comment by codingquark** [comment]
@HungFFC give link to your github repo, someone might be able to look at the code and help.

I understand that you are not comfortable with English, which might be a reason why you think there is no documentation. In reality, readme is quite informative, and all the code is commented too.

**Comment by louis-hoang21** [comment]
@codingquark 
hi codingquark
My english is very badly.
So i need example code to better understand the package. 
I hope you can help me understand it. Thank you.
