### ISSUE TITLE
can't install your package to my laravel project 

### ISSUE THREAD

**Issue by jagdishabhiandroid** [Oviyum/laravel-otp#8]
when try to install getting this error 

[InvalidArgumentException]
  Could not find package fleetfoot/otp.

  Did you mean this?
      fleetfoot/otp

**Comment by codingquark** [comment]
Can you provide more details?
1. When does this happen?
2. What exactly are you typing
3. Which version of Laravel are you using
4. Anything else we should know about what you're trying to do?
